### PR TITLE
Remove typing package

### PR DESCRIPTION
**Pull request by marcosfelt**
Typing causes problems on many recent python versions (3.7+). It should be removed.

https://github.com/python/typing/issues/573

### CODE REVIEW

**Review by michaelosthege — APPROVED** [review]
Hi Kobi,
Thanks for niticing this. Indeed, the `typing` package is in the standard library and should not appear in the requirements.
cheers

**Comment by marcosfelt** [comment]
If possible, could you do a minor version bump on pypi?

**Comment by michaelosthege** [comment]
@marcosfelt done!

**Comment by marcosfelt** [comment]
Thank you!!

**Pull request merged**
